[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    olikraus/U8g2
build_src_filter =
    +<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>
    -<ldr_module_test.cpp>
    -<dht22_test.cpp>
    -<oled_test.cpp>
    -<oled_sh1106_combo_test.cpp>
    -<room_panel_test.cpp>
    -<room_panel_u8x8_test.cpp>

[env:led_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
build_src_filter =
    +<led_test.cpp>
    -<main.cpp>

[env:buzzer_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
build_src_filter =
    +<buzzer_test.cpp>
    -<main.cpp>
    -<led_test.cpp>

[env:ldr_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
build_src_filter =
    +<ldr_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>

[env:ldr_module_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
build_src_filter =
    +<ldr_module_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>

[env:dht22_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
build_src_filter =
    +<dht22_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>
    -<ldr_module_test.cpp>

[env:oled_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
build_src_filter =
    +<oled_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>
    -<ldr_module_test.cpp>
    -<dht22_test.cpp>

[env:oled_sh1106_combo_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
lib_deps =
    adafruit/Adafruit SH110X
    adafruit/Adafruit GFX Library
build_src_filter =
    +<oled_sh1106_combo_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>
    -<ldr_module_test.cpp>
    -<dht22_test.cpp>
    -<oled_test.cpp>

[env:room_panel_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit SH110X
    adafruit/Adafruit GFX Library
build_src_filter =
    +<room_panel_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>
    -<ldr_module_test.cpp>
    -<dht22_test.cpp>
    -<oled_test.cpp>
    -<oled_sh1106_combo_test.cpp>

[env:room_panel_u8x8_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    olikraus/U8g2
build_src_filter =
    +<room_panel_u8x8_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>
    -<ldr_module_test.cpp>
    -<dht22_test.cpp>
    -<oled_test.cpp>
    -<oled_sh1106_combo_test.cpp>
    -<room_panel_test.cpp>

[env:button_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM6
build_src_filter =
    +<button_test.cpp>
    -<main.cpp>
    -<led_test.cpp>
    -<buzzer_test.cpp>
    -<ldr_test.cpp>
    -<ldr_module_test.cpp>
    -<dht22_test.cpp>
    -<oled_test.cpp>
    -<oled_sh1106_combo_test.cpp>
    -<room_panel_test.cpp>
    -<room_panel_u8x8_test.cpp>
